### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by gld1982ltd** [giucam/termistor#1]
`[ 77%] Building CXX object CMakeFiles/termistor.dir/src/screen.cpp.o
/home/gld1982ltd/dev/termistor-master/src/screen.cpp: In member function ‘void Screen::render(QPainter*)’
/home/gld1982ltd/dev/termistor-master/src/screen.cpp:309:45: error: ‘tsm_vte_get_def_attr’ was not declared in this scope
     tsm_vte_get_def_attr(m_vte->vte(), &attr);
                                             ^`

**Comment by giucam** [comment]
Can you try building libtsm from git?

**Comment by gld1982ltd** [comment]
Fixed it
