### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by anordal** [giucam/termistor#2]
Having compiled and installed it, there is no window when I run termistor. Is it supposed to slide down when hitting some magical key combo? Tried all the F-buttons.

As a clueless first-time user, I would appreciate a word or 2 in --help or README.md.

Thanks for your efforts so far.

**Comment by giucam** [comment]
If you use it in Orbital pressing F12 should show it, otherwise it should show up as a normal window. You can also force it to be a normal window using the -w option.

**Comment by anordal** [comment]
I don't get a window with the -w option either. (Not using Orbital, just plain weston.)

**Comment by giucam** [comment]
Ok, so with weston it should show a normal window even when not using -w. Can you paste here the output you get when exporting WAYLAND_DEBUG=1?

**Comment by anordal** [comment]
I get no output. The debug method works with other programs like weston-terminal and otter-browser.

What I get, is this process tree in htop. Termistor has got 2 process IDs. They are not using any CPU. Job control wise, termistor is running in the foreground.

```
weston-terminal
└─ fish
   └─ termistor
      └─ termistor
```

**Comment by giucam** [comment]
Well, that is weird. Are you sure you're using the wayland platform plugin? I.e. "termistor -platform wayland" or "export QT_QPA_PLATFORM=wayland".

**Comment by anordal** [comment]
That's it! I forgot -platform wayland. There was no error message because I was running X at the same time. You know what? Termistor works in X too!
