### ISSUE TITLE
workarounds for header finding

### ISSUE THREAD

**Issue by anordal** [giucam/termistor#3]
In order to compile, I had to substitute these includes,

``` diff
diff --git src/main.cpp:
-#include <wayland-client.h>
+#include <wayland/wayland-client.h>
```

``` diff
diff --git src/vte.cpp:
-#include <xkbcommon/xkbcommon-keysyms.h>
+#include <pkg/libxkbcommon/xkbcommon/xkbcommon-keysyms.h>
```

and in the build directory, create these proxy header files:
- wayland-client.h containing `#include <wayland/wayland-client.h>`
- wayland-util.h containing `#include <wayland/wayland-util.h>`

The proxy headers were needed because generated sources were including from their own directory:

```
/tmp/build-termistor> grep '#include "wayland' -r .
./wayland-dropdown-protocol.c:#include "wayland-util.h"
./wayland-dropdown-client-protocol.h:#include "wayland-client.h"
```

**Comment by giucam** [comment]
Can you check if it is fixed now?

**Comment by anordal** [comment]
Almost! I still have to edit vte.cpp, but that's it.

**Comment by anordal** [comment]
This should fix the rest (works for me):

``` diff
 pkg_check_modules(libtsm libtsm REQUIRED)
 pkg_check_modules(wayland-client wayland-client REQUIRED)
+pkg_check_modules(xkbcommon xkbcommon REQUIRED)

 set(CMAKE_AUTOMOC ON)
 foreach(dir ${Qt5Gui_INCLUDE_DIRS})
     include_directories(${dir}/${Qt5Gui_VERSION_STRING}/QtGui/)
 endforeach(dir)
 include_directories(${wayland-client_INCLUDE_DIRS})
+include_directories(${xkbcommon_INCLUDE_DIRS})
```

According to my package manager (zypper), `pkg/libxkbcommon/xkbcommon/xkbcommon-keysyms.h` comes from the package `libxkbcommon-devel`. Hence the package name in the patch.

**Comment by giucam** [comment]
Thanks, i pushed that change.
